[theme]
primaryColor = "#979593"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1D23"
textColor = "#0a0909"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = true
